---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carstaxi-feedback-voc
  labels:
    app: carstaxi-feedback-voc
spec:
  selector:
    matchLabels:
      app: carstaxi-feedback-voc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: carstaxi-feedback-voc
    spec:
      containers:
        - name: carstaxi-feedback-voccnt
          image: 029561271011.dkr.ecr.me-south-1.amazonaws.com/feedback:{BUILD_ID}
          volumeMounts:
          - name: app-config
            mountPath: /app/build/appConfig.js
            subPath: appConfig.js
            readOnly: true
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: TZ
              value: Asia/Dubai
      volumes:
        - name: app-config
          configMap:
            name: carstaxi-feedback-voc
---
apiVersion: v1
kind: Service
metadata:
  name: carstaxi-feedback-voc
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: carstaxi-feedback-voc
